### ISSUE TITLE
`filterFasta` for canonical peptides

### ISSUE THREAD

**Issue by lydiayliu** [uclahs-cds/package-moPepGen#698]
As titled, essentially filtering canonical peptides by transcript expression, just as we have done for the noncanonical peptides. Could be added to `filterFasta`?

**Comment by zhuchcn** [comment]
We actually don't have a way to generate a canonical peptide fasta file. `generateIndex` does generate canonical peptide pool, but I didn't save it into a FASTA file. What was the purpose of this in your mind back then?

**Comment by lydiayliu** [comment]
I have no idea what i was thinking lol. We don't actually generate a canonical proteome FASTA at all. But i suppose we can filter the proteome.fasta (part of the index) for canonical database search. Otherwise, maybe filter the canonical peptides by expression before using them as the denylist in callVariant?

**Comment by zhuchcn** [comment]
I see. If we provide a denylist of low-expression transcripts and assume no canonical proteins/peptides are produced, should we also exclude those transcripts when calling variant peptides?

**Comment by lydiayliu** [comment]
i think those transcripts would be filtered out with filterFasta anyways?

**Comment by zhuchcn** [comment]
OK let's close this for now.
