### ISSUE TITLE
Coordinate of Noncaonincal Peptide

### ISSUE THREAD

**Issue by zhuchcn** [uclahs-cds/package-moPepGen#833]
We currently don't have a very easy approach to get the coordinate of the noncanonical peptide either at the original transcript level or at the genomic scale. We only know that the variant(s) that the peptide carries is inside the peptide range or upstream to it (frameshifting, stop lost, cleavage lost, etc), but it's no easy to get the exact location of the peptide. I can do this case by case to take the transcript and translate it into peptide and search for the peptide, but a better solution is needed if we want to look at more peptides.

The information we might need to fully represent that transcript or genomic coordinate of a noncanonical peptides includes:

1. The transcript coordinate of each segment on the peptide that does not have any variant.
2. The last upstream transcript coordinate
3. The first downstream transcript coordinate

1 is used to map the peptide to the original transcript, and 2 & 3 will be useful if the entier peptide is from an inserted nucleotide sequence.

**Comment by zhuchcn** [comment]
Consider putting this information in a separate file along with the variant FASTA file.

**Comment by zhuchcn** [comment]
Not sure if this is a good idea. We could write a tsv file along with the variant fasta. For example, we have a peptide like below.

![image](https://github.com/uclahs-cds/package-moPepGen/assets/29579625/82ddd10f-f492-481d-a662-79fe105ccdf5)

This peptide has 2 variants, a SNV `SNV-100-T/A` and a retained intron of `RI-214-300`. We can then represent this peptide as below, as 4 segments that can be mapped to either a transcript/gene location, or a variant. With this, we then can easily get the more information of this peptide. We can easily do things such as find all peptides that span over the backsplicing site of any circRNA.

```
sequence    start    end    feature_type    feature       ref_start    ref_end    start_offset    end_offset    variant
AAAAAAA     0        3      transcript      ENST0001.2    100          107        0               -2            .
AAAAAAA     2        3      .               .             .            .          1               -1            SNV-107-A-T
AAAAAAA     2        5      transcript      ENST0001.2    109          114        2               -1            .
AAAAAAA     4        7      gene            ENSG0001      214          219        2               0             RI-XXX-XXX
```

- `sequence`: The peptide sequence
- `start`: The start position of the peptide
- `end`: The end position of the the peptide
- `ref_type`: The type of reference that this segment is mapped to, either transcript or gene.
- `ref_name`: The feature name of the reference location that the segment is mapped to. This will be the transcript ID or gene ID corresponding to `ref_type`.
- `ref_start`: The start position of the reference sequence on transcript or gene
- `ref_end`: The end position of the reference sequence on transcript or gene
- `start_offset`: The nucleotide offset from the beginning in the first codon that matches with `ref_start`
- `end_offset`: The nucleotide offset from the end in the last codon that matches with `ref_end`.
- `variant`: Variant. Empty if no variant.

**Comment by lydiayliu** [comment]
I would suggest adding a column that displays the peptide substring, to save all the time counting characters lol

> ref_start: The start position of the reference sequence on transcript or gene

In what cases would the reference sequence be a transcript and which case would it be a gene?

Sorry can you explain more how `start_offset` and `end_offset` works?

**Comment by zhuchcn** [comment]
> I would suggest adding a column that displays the peptide substring, to save all the time counting characters lol

That's a good suggestion. I was worried about the extra string manipulation but should be OK.

> In what cases would the reference sequence be a transcript and in which case would it be a gene?

The coordinate will be gene in 3 cases: 
1. Alternative splicing insertions and substitutions. The inserted sequences are represented in the gene coordinate.
2. Fusion that the donor and/or accepter breakpoints are intronic. Peptides translated from the inserted introns are also in the gene coordinates.
3. circRNA

> Sorry can you explain more how start_offset and end_offset works?

Explained in https://github.com/uclahs-cds/package-moPepGen/pull/856#issuecomment-1975644302

**Comment by lydiayliu** [comment]
> That's a good suggestion. I was worried about the extra string manipulation but should be OK.

But you are basically asking users to do string manipulation in their heads? XD what are the concerns?

**Comment by zhuchcn** [comment]
My concern was about performance. Too much string manipulation can make the runtime really bad for high-complexity cases, but I managed to extract the substring in the end of the graph manipulation so it doesn't add too much computation overall. This is already added. See https://github.com/uclahs-cds/package-moPepGen/issues/833#issuecomment-1974291789 . I updated the comment.
