### ISSUE TITLE
Format requirement of VEP

### ISSUE THREAD

**Issue by hsiaoyi0504** [uclahs-cds/package-moPepGen#882]
When reading documentation, I am a little confused about what's the exact input file expected for `parseVEP`:

- The file used in the test is the default VEP output format:
https://github.com/uclahs-cds/package-moPepGen/blob/6744e7dd91dd8741b92314bec3ca6f4d4785992d/test/integration/test_parse_vep.py#L16

- Description here seems to imply that the input file should be tsv
https://github.com/uclahs-cds/package-moPepGen/blob/6744e7dd91dd8741b92314bec3ca6f4d4785992d/docs/parse-vep.md?plain=1#L32

The major confusion is that both default VEP format and tab format (using `--tab`) are both tab-delimited file.
https://www.ensembl.org/info/docs/tools/vep/vep_formats.html

**Comment by zhuchcn** [comment]
parseVEP only uses the first 13 columns of VEP output. `--tab` adds a header and several additional columns not used by moPepGen. So both with and without `--tab` is fine.
